### ISSUE TITLE
no preview and errors with FIJI 64bit and phantast

### ISSUE THREAD

**Issue by sbaird57** [nicjac/PHANTAST-FIJI#4]
I realize this plugin is a few years old. Is there any fixes for using it properly in FIJI imagej 1.51n on Win7 with Phantast 0.2 to get the preview ability.
![image](https://user-images.githubusercontent.com/37191192/37170045-bf7b2aca-22d7-11e8-953b-d638c47cf994.png)
from the log when I click on checkbox:
ERROR: java.lang.NullPointerException
in DialogListener of PHANTAST_@7f406c0c
at PHANTAST_.dialogItemChanged(PHANTAST_.java:160)
from ij.gui.GenericDialog.notifyListeners(GenericDialog.java:1426)

from the console:
Exception in thread "Open" java.lang.UnsupportedOperationException: Attempting to read or write from a io.scif.io.VirtualHandle. There is no source to operate on.
	at io.scif.io.VirtualHandle.read(VirtualHandle.java:83)
	at io.scif.io.RandomAccessInputStream.read(RandomAccessInputStream.java:437)
	at io.scif.formats.KontronFormat$Checker.isFormat(KontronFormat.java:124)
	at io.scif.AbstractChecker.isFormat(AbstractChecker.java:93)
	at io.scif.services.DefaultFormatService.getFormatList(DefaultFormatService.java:342)
	at io.scif.services.DefaultFormatService.getFormat(DefaultFormatService.java:317)
	at io.scif.services.DefaultDatasetIOService.canOpen(DefaultDatasetIOService.java:83)
	at io.scif.io.DatasetIOPlugin.supportsOpen(DatasetIOPlugin.java:65)
	at org.scijava.io.IOService.getOpener(IOService.java:56)
	at net.imagej.legacy.plugin.DefaultLegacyOpener.open(DefaultLegacyOpener.java:131)
	at net.imagej.legacy.DefaultLegacyHooks.interceptFileOpen(DefaultLegacyHooks.java:332)
	at ij.IJ.open(IJ.java)
	at ij.text.TextPanel.run(TextPanel.java:328)
	at java.lang.Thread.run(Thread.java:745)

**Comment by sbaird57** [comment]
Just did an update to imageJ 1.51v and it is now working
